apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apps.bruce.kennethreitz.org
spec:
  group: bruce.kennethreitz.org
  names:
    kind: App
    listKind: appList
    plural: apps
    singular: app
  scope: Namespaced
  version: v1alpha1
