apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: buildpacks-volume
  name: buildpacks-volume
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
status: {}
