apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: buildpacks.bruce.kennethreitz.org
spec:
  group: bruce.kennethreitz.org
  names:
    kind: Buildpack
    listKind: buildpackList
    plural: buildpacks
    singular: buildpack
    shortNames: [bp,]
  scope: Namespaced
  version: v1alpha1
