apiVersion: v1
items:
- apiVersion: bruce.kennethreitz.org/v1alpha1
  kind: Buildpack
  metadata:
    name: "ruby"
    buildkit: "heroku/ruby"
- apiVersion: bruce.kennethreitz.org/v1alpha1
  kind: Buildpack
  metadata:
    name: "nodejs"
    buildkit: "heroku/nodejs"
- apiVersion: bruce.kennethreitz.org/v1alpha1
  kind: Buildpack
  metadata:
    name: "clojure"
    buildkit: "heroku/clojure"
- apiVersion: bruce.kennethreitz.org/v1alpha1
  kind: Buildpack
  metadata:
    name: "python"
    buildkit: "heroku/python"
- apiVersion: bruce.kennethreitz.org/v1alpha1
  kind: Buildpack
  metadata:
    name: "java"
    buildkit: "heroku/java"
- apiVersion: bruce.kennethreitz.org/v1alpha1
  kind: Buildpack
  metadata:
    name: "gradle"
    buildkit: "heroku/gradle"
- apiVersion: bruce.kennethreitz.org/v1alpha1
  kind: Buildpack
  metadata:
    name: "scala"
    buildkit: "heroku/scala"
- apiVersion: bruce.kennethreitz.org/v1alpha1
  kind: Buildpack
  metadata:
    name: "php"
    buildkit: "heroku/php"
- apiVersion: bruce.kennethreitz.org/v1alpha1
  kind: Buildpack
  metadata:
    name: "go"
    buildkit: "heroku/go"
- apiVersion: bruce.kennethreitz.org/v1alpha1
  kind: Buildpack
  metadata:
    name: "elixir"
    buildkit: "hashnuke/elixir"
- apiVersion: bruce.kennethreitz.org/v1alpha1
  kind: Buildpack
  metadata:
    name: "static"
    repo: "https://github.com/dokku/buildpack-nginx"
- apiVersion: bruce.kennethreitz.org/v1alpha1
  kind: Buildpack
  metadata:
    name: "multi"
    repo: "https://github.com/heroku/heroku-buildpack-multi"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
