apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\me\OneDrive\system\bin\kompose.exe convert -f .\kubernetes-compose.yml
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: registry
  name: registry
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 80
    targetPort: 0
  selector:
    io.kompose.service: registry
status:
  loadBalancer: {}
