apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\me\OneDrive\system\bin\kompose.exe convert -f .\kubernetes-compose.yml
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: registry
  name: registry
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: registry
    spec:
      containers:
      - env:
        - name: REGISTRY_HTTP_ADDR
          value: 0.0.0.0:80
        image: registry:2
        name: registry
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/registry
          name: bruce-registry-data
      restartPolicy: Always
      volumes:
      - name: bruce-registry-data
        persistentVolumeClaim:
          claimName: bruce-registry-data
status: {}
